name: canada-map-app
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dash=2.11.1
  - plotly=5.18.0
  - geopandas=0.14.1
  - pandas=2.1.4
  - gdal=3.7.2
  - pip
  - pip:
    - python-rapidjson==1.10
    - voila

services:
  - type: web
    name: canada-dash-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
